site_name: CBM-DF
nav:
  - Home: index.md
  - Planejamento: ponto_de_controle_1/Planejamento.md
  - Ponto de controle 1:
    - Processos de Design: ponto_de_controle_1/Processo_de_Design.md
    - Ferramentas utilizadas: ponto_de_controle_1/ferramentas_utilizadas.md
    - Sites analisados: ponto_de_controle_1/sites_analisados.md
    - Apresentacao: ponto_de_controle_1/apresentacao_pc1.md
  - Ponto de controle 2:
    - Personas: ponto_de_controle_2/personas.md
    - Perfil de usuario: ponto_de_controle_2/perfil_de_usuários.md
    - Analise de Tarefas: ponto_de_controle_2/analise_tarefas.md
    - Apresentacao: ponto_de_controle_2/apresentacao_pc2.md
  - Ponto de controle 3:
      - Principios e diretrizes: ponto_de_controle_3/Principios_diretrizes.md
      - Metas de Usabilidade: ponto_de_controle_3/metas_usabilidade.md
theme:
  name: material
  custom_dir: docs/images
  language: pt
  palette:
    scheme: default
    primary: red
    accent: deep orange
  font:
    text: Roboto